apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NaveenBalagouni/Kustomization.git'  # Git repository with Kustomize configs
    targetRevision: HEAD  # The branch to track (e.g., main or master)
    path: 'kustomize/overlays/dev'  # Path to dev overlay or use prod overlay
    kustomize:
      namePrefix: "kustomize-"  # Optionally add a prefix to all resources
  destination:
    server: 'https://kubernetes.default.svc'  # Kubernetes cluster API server URL
    namespace: kustomize-naveen  # Namespace where the resources will be deployed
  syncPolicy:
    automated:
      prune: true  # Automatically prune resources that are no longer in Git
      selfHeal: true  # Automatically fix any drift in the cluster
    syncOptions:
      - CreateNamespace=true  # Automatically create the namespace if it doesn't exist
